baseURL = "https://77doc.github.io/"
languageCode = "zh-cn"
theme = "hugo-book"
title = "企企生存手册"
#publishDir = "docs"

[markup]
    defaultMarkdownHandler = "goldmark"
    [markup.goldmark]
        [markup.goldmark.extensions]
            definitionList = true
            footnote = true
            linkify = true
            strikethrough = true
            table = true
            taskList = true
            typographer = false
        [markup.goldmark.renderer]
            hardWraps = false
            unsafe = true
            xHTML = false
    [markup.highlight]
    [markup.tableOfContents]
        startLevel = 2
        endLevel = 6
        ordered = false
